---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: MegaLinter
on:
  # Trigger mega-linter at every push. Action will also be visible from Pull Requests to main
  # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  push:
    branches:
      - main
        # github_api_key_path:
        #  required: true
        #  type: string
        #  description: The GHA Api key
env:  # Comment env block if you don't want to apply fixes
  APPLY_FIXES: all  # When active, APPLY_FIXES must also be defined as environment variable (in github/workflows/mega-linter.yml or other CI tool)
jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    # permissions:
    #  # Give the default GITHUB_TOKEN write permission to commit and push, comment issues & post new PR
    #  # Remove the ones you do not need
    #  contents: write
    #  issues: write
    #  pull-requests: write
    steps:
      - name: Determine name of MegaLinter Docker image from pre-commit config.
        id: megalinter
        run: |
          from os import environ
          from re import compile

          _MEGALINTER_ARGS_PATTERN = compile(
              "args:\\s*&megalinter-args\\s*\\[--flavor,\\s*(?P<flavor>\\w+),"
              "\\s*--release,\\s*(?P<release>v(\\d+\\.){2}\\d+)"
          )
          with open(".pre-commit-config.yaml", encoding="utf-8") as input_stream:
              for line in input_stream:
                  if match := _MEGALINTER_ARGS_PATTERN.search(line):
                      break

          flavor = match.group("flavor")
          release = match.group("release")
          docker_image = f"megalinter-{flavor}:{release}"
          output_file = environ["GITHUB_OUTPUT"]
          with open(output_file, "a", encoding="utf-8") as output_stream:
              output_stream.write(f"DOCKER_IMAGE={docker_image}\n")
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.6
        with:
          key: ${{ steps.megalinter.outputs.DOCKER_IMAGE }}
      #  Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to improve performances

      # MegaLinter
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/flavors/
        uses: oxsecurity/megalinter@v7
        env:
          # All available variables are described in documentation
          # https://megalinter.io/configuration/
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}  # Validates all source when push on main, else just the git diff with main. Override with true if you always want to lint all sources
      # ADD YOUR CUSTOM ENV VARIABLES HERE OR DEFINE THEM IN A FILE .mega-linter.yml AT THE ROOT OF YOUR REPOSITORY
      # DISABLE: COPYPASTE,SPELL  # Uncomment to disable copy-paste and spell checks

      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log

